spring:
  mqtt:
    broker: tcp://127.0.0.1:1883
    clientId: 123456 #客户端的id
    username: admin
    password: public
    timeout: 2000
    KeepAlive: 20
    topics: test1 #主题
    qos: 1 #心跳包级别
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.50.158.67:3306/sp-monitor?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: etmonitor@7qTzSW#R
mybatis:
  config-location: classpath:static/mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.example.emqdemo.mapper: debug # 要改成要打印的sql语句所在的mapper文件所在包路径
